# payment_gateway.py
import stripe
from django.conf import settings

# Initialize Stripe API key
stripe.api_key = settings.STRIPE_SECRET_KEY

class StripePaymentGateway:
    @staticmethod
    def charge(amount, token, description):
        try:
            # Create a charge using the Stripe API
            charge = stripe.Charge.create(
                amount=amount,  # Amount in cents
                currency='usd',  # Currency code
                source=token,  # Token generated by Stripe.js or Checkout
                description=description,
            )
            # If charge is successful, return True
            return True, None
        except stripe.error.StripeError as e:
            # If there's an error during charging, return False and error message
            return False, str(e)
